# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-01 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_number',
        ),
    ]
